---
title: "Introduction des données"
title-block-banner: true
description: | 
  Description description du projet.
# à changer
date: "2022-12-20"
# Modifier les détails que vous voulez
author:
  - name: "Rémi Turcot-Roy"
    # Votre site web perso ou github
    url: https://github.com/rTurcotroy
    # les champs d'affiliation sont optionnels, vous pouvez les
    # comment out en ajoutant un # devant.
    affiliation: FAS1002
    affiliation-url: https://FAS1002.github.io/A22
    # changer pour votre propre orcid id
    # https://orcid.org/ pour vous inscrire.
    orcid: 0000-0000-0000-0000

# TRUE == Générer une citation pour cette page précise. Pour enlever, mettre false.
citation: true
# Inclure les références que vous utilisez dans vos rapports. Je conseille Zotero pour construire
# ce fichier ou de connecter RStudio directement pour pouvoir citer avec @nom-de-reference.
bibliography: references.bib
---

Ce projet a donc pour but de démontrer les nouvelles connaissances que nous avons acquises au cours de la session. Pour cela, j'ai téléchargé directement les données via l'URL des bases de données et validé la récurrence de ceux-ci. Pour faciliter cette étape, j'ai créé une fonction qui prend le nom, l'URL et la récurrence du téléchargement. Cette procédure fonctionne bien sauf pour les données en provenance de gapminder puisque le lien URL de téléchargement demandait un accès restreint.

Par la suite, l'analyse est faite via l'intégration de trois bases de données vers une variable. Cette base de données est donc par la suite modifiée pour traiter les variables qui nous intéressent. Dans le cadre de cette analyse nous voulions regarder la progression des variables co2, espérance de vie, demande en énergie à travers les années. Cela dans le but de comprendre ce qui peut influencer l'espérance de vie. Nous avons aussi créé une nouvelle variable soit le continent en prenant comme référent le pays. Cela permet donc de faire des visualisations plus claires en utilisant les continents comme variable de localisation. Il a aussi important de retirer les variables manquantes. Ce qui a tout de même un certain impacte sur les résultats.

Les données proviennent entre autres de:

@owidenergy

@gaplife

@owidco2
